const fs   = require('fs');
const path = require('path');

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  fs.readdirSync(src).forEach(function (file) {
    var s = path.join(src, file);
    var d = path.join(dest, file);
    fs.statSync(s).isDirectory() ? copyDir(s, d) : fs.copyFileSync(s, d);
  });
}

// ── Read .env (optional) → KEY=VALUE map ──
function loadEnv() {
  var env = {};
  try {
    fs.readFileSync('.env', 'utf8').split(/\r?\n/).forEach(function (line) {
      line = line.trim();
      if (!line || line[0] === '#') return;
      var i = line.indexOf('=');
      if (i === -1) return;
      env[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    });
  } catch (e) { /* no .env present — fine, values default to empty */ }
  return env;
}

// ── Generate client config (js/config.js) from .env ──
// The Formspree ID is public by design (visible in the network request); this
// keeps it out of source control and in one place, not a security boundary.
var env = loadEnv();

// GitHub Pages serves this repo's ROOT, so js/config.js is the file the live
// site actually loads — it is committed, not a build artifact. A build without
// a .env must therefore never blank a working ID; that is exactly how the
// contact form silently stopped emailing. Fall back to whatever is already
// committed, and only overwrite when .env supplies a value.
function currentId() {
  try {
    var m = fs.readFileSync('js/config.js', 'utf8').match(/formspreeId:\s*"([^"]*)"/);
    return m ? m[1] : '';
  } catch (e) { return ''; }
}
var formspreeId = env.FORMSPREE_ID || currentId();
if (!env.FORMSPREE_ID && formspreeId) {
  console.log('note: no .env — keeping the committed Formspree ID');
} else if (!formspreeId) {
  console.warn('WARNING: no Formspree ID. The contact form will fall back to WhatsApp.');
}
var configJs =
  '/* AUTO-GENERATED by build.js from .env — do not edit by hand. */\n' +
  'window.ENZO_CONFIG = {\n' +
  '  formspreeId: ' + JSON.stringify(formspreeId) + '\n' +
  '};\n';
fs.writeFileSync('js/config.js', configJs);
console.log('generated → js/config.js');

// ── Sync shared partials into every page ──
// GitHub Pages serves this repo's ROOT, so the root .html files are the site.
// Header, mobile nav and footer used to be hand-copied into all 63 of them --
// 31% of the HTML was that repetition, and a nav change meant editing 63 files.
// They now live in partials/ and are written back between the <!--#name--> and
// <!--/#name--> markers on each page. The markup emitted is byte-for-byte what
// was there before; {{BASE}} resolves the ../ that journal pages need, and the
// header keeps whatever class the page already carried (is-static / over-hero).
function syncPartials() {
  var names = ['header', 'mobile-nav', 'footer'];
  var parts = {};
  names.forEach(function (n) {
    parts[n] = fs.readFileSync(path.join('partials', n + '.html'), 'utf8');
  });

  var files = fs.readdirSync('.')
    .filter(function (f) { return f.endsWith('.html'); })
    .concat(fs.readdirSync('journal').map(function (f) { return path.join('journal', f); }));

  var touched = 0;
  files.forEach(function (file) {
    var html = fs.readFileSync(file, 'utf8');
    if (html.indexOf('<!--#header-->') === -1) return;   // redirect stubs carry no chrome
    var base = file.indexOf(path.sep) === -1 ? '' : '../';
    var headerClass = (html.match(/<header class="site-header ([^"]+)"/) || [])[1] || 'is-static';
    var before = html;

    names.forEach(function (n) {
      var body = parts[n]
        .replace(/\{\{BASE\}\}/g, base)
        .replace(/\{\{HEADER_CLASS\}\}/g, headerClass);
      var re = new RegExp('<!--#' + n + '-->[\\s\\S]*?<!--/#' + n + '-->');
      html = html.replace(re, '<!--#' + n + '-->\n' + body + '\n<!--/#' + n + '-->');
    });

    if (html !== before) { fs.writeFileSync(file, html); touched++; }
  });
  console.log('partials → synced into ' + files.length + ' pages (' + touched + ' rewritten)');
}
syncPartials();

// ── Build dist/ (pages carry the synced partials; no further injection) ──
var pages = [
  'index', 'about', 'catalog', 'calculator', 'contact', 'wholesale',
  'shop', 'journal', 'fibre', 'product-safa', 'product-noor', 'product-waqar', 'product-daim'
];

// Clean dist so removed source files never linger in the artifact.
// rmSync can hit EPERM on Windows if a file is briefly locked — retry, then
// fall back to best-effort so the build still produces an up-to-date artifact.
try {
  fs.rmSync('dist', { recursive: true, force: true, maxRetries: 5, retryDelay: 120 });
} catch (e) {
  console.warn('warning: could not fully clean dist/ (' + e.code + ') — continuing');
}
fs.mkdirSync('dist', { recursive: true });

pages.forEach(function (page) {
  fs.copyFileSync(page + '.html', 'dist/' + page + '.html');
  console.log('copied → dist/' + page + '.html');
});

copyDir('assets',    'dist/assets');
copyDir('js',        'dist/js');   // includes the generated config.js
copyDir('data',      'dist/data');
copyDir('journal',   'dist/journal');   // long-form article pages behind journal.html
copyDir('raqi-site', 'dist/raqi-site'); // old RAQI URLs — redirect stubs, not a live app

// css/components.css is appended onto output.css by `npm run build:css`
// (one stylesheet request per page instead of two) — not copied standalone.

['robots.txt', 'sitemap.xml'].forEach(function (f) {
  if (fs.existsSync(f)) fs.copyFileSync(f, 'dist/' + f);
});
console.log('copied → assets/ js/ data/ journal/ raqi-site/ + SEO files');
